# Generated by Django 5.2.17 on 2026-10-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('description', models.TextField(max_length=250)),
                ('cover', models.FileField(blank=True, null=True, upload_to='')),
                ('author', models.ManyToManyField(blank=True, related_name='authors', to='author.author')),
            ],
        ),
        migrations.CreateModel(
            name='BookUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=16, unique=True)),
                ('borrowed', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_units', to='books.book')),
            ],
        ),
    ]
