# Generated by Django 5.2.17 on 2026-10-05 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0001_initial'),
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_date', models.DateTimeField(auto_now_add=True)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('person_type', models.CharField(choices=[('ST', 'Student'), ('TE', 'Teacher'), ('VI', 'Visitor')], default='ST', max_length=2)),
                ('book_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookunit')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='person.person')),
            ],
        ),
    ]
